// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhxeczhkwirktthgeuxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oeGVjemhrd2lya3R0aGdldXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNTc0ODUsImV4cCI6MjA2ODYzMzQ4NX0.Zqe2A66r3twbN_2pCenW52XD_CsK0ELnDEEigYWdkUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});